swagger: '2.0'
info:
  version: '1.0'
  title: "Short URL"
schemes:
  - https
paths:
  "/":
    get:
      description: "Home"
      produces:
        - application/json
      x-amazon-apigateway-integration:
        uri: ${lambda_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  "/graphql":
    get:
      description: "Graphql Playground"
      produces:
        - application/xml
      responses:
        200:
          description: "graphql playground"
      x-amazon-apigateway-integration:
        uri: ${lambda_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
    post:
      description: "Graphql Playground"
      consumes:
        - application/json
      responses:
        200:
          description: "Graphql Playground"
      x-amazon-apigateway-integration:
        uri: ${lambda_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  "/api":
    get:
      description: "REST APIs"
      produces:
        - application/json
      responses:
        200:
          description: "REST APIs"
      x-amazon-apigateway-integration:
        uri: ${lambda_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
    post:
      description: "REST APIs"
      consumes:
        - application/json
      responses:
        200:
          description: "REST APIs"
      x-amazon-apigateway-integration:
        uri: ${lambda_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"